/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallStreetReportRouteImport } from './routes/wall-street-report'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as MyApiRouteImport } from './routes/my-api'
import { Route as AiPilotRouteImport } from './routes/ai-pilot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignalsIndexRouteImport } from './routes/signals/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as QuantRlLabRouteImport } from './routes/quant/rl-lab'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AgentsDeskRouteImport } from './routes/agents/desk'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'

const WallStreetReportRoute = WallStreetReportRouteImport.update({
  id: '/wall-street-report',
  path: '/wall-street-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApiRoute = MyApiRouteImport.update({
  id: '/my-api',
  path: '/my-api',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPilotRoute = AiPilotRouteImport.update({
  id: '/ai-pilot',
  path: '/ai-pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIndexRoute = SignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantRlLabRoute = QuantRlLabRouteImport.update({
  id: '/quant/rl-lab',
  path: '/quant/rl-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDeskRoute = AgentsDeskRouteImport.update({
  id: '/agents/desk',
  path: '/agents/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-pilot': typeof AiPilotRoute
  '/my-api': typeof MyApiRoute
  '/pending': typeof PendingRoute
  '/pricing': typeof PricingRoute
  '/wall-street-report': typeof WallStreetReportRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/agents/desk': typeof AgentsDeskRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quant/rl-lab': typeof QuantRlLabRoute
  '/admin/': typeof AdminIndexRoute
  '/signals/': typeof SignalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-pilot': typeof AiPilotRoute
  '/my-api': typeof MyApiRoute
  '/pending': typeof PendingRoute
  '/pricing': typeof PricingRoute
  '/wall-street-report': typeof WallStreetReportRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/agents/desk': typeof AgentsDeskRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quant/rl-lab': typeof QuantRlLabRoute
  '/admin': typeof AdminIndexRoute
  '/signals': typeof SignalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-pilot': typeof AiPilotRoute
  '/my-api': typeof MyApiRoute
  '/pending': typeof PendingRoute
  '/pricing': typeof PricingRoute
  '/wall-street-report': typeof WallStreetReportRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/agents/desk': typeof AgentsDeskRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quant/rl-lab': typeof QuantRlLabRoute
  '/admin/': typeof AdminIndexRoute
  '/signals/': typeof SignalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-pilot'
    | '/my-api'
    | '/pending'
    | '/pricing'
    | '/wall-street-report'
    | '/admin/activity'
    | '/admin/permissions'
    | '/admin/security'
    | '/agents/desk'
    | '/auth/callback'
    | '/quant/rl-lab'
    | '/admin/'
    | '/signals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-pilot'
    | '/my-api'
    | '/pending'
    | '/pricing'
    | '/wall-street-report'
    | '/admin/activity'
    | '/admin/permissions'
    | '/admin/security'
    | '/agents/desk'
    | '/auth/callback'
    | '/quant/rl-lab'
    | '/admin'
    | '/signals'
  id:
    | '__root__'
    | '/'
    | '/ai-pilot'
    | '/my-api'
    | '/pending'
    | '/pricing'
    | '/wall-street-report'
    | '/admin/activity'
    | '/admin/permissions'
    | '/admin/security'
    | '/agents/desk'
    | '/auth/callback'
    | '/quant/rl-lab'
    | '/admin/'
    | '/signals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPilotRoute: typeof AiPilotRoute
  MyApiRoute: typeof MyApiRoute
  PendingRoute: typeof PendingRoute
  PricingRoute: typeof PricingRoute
  WallStreetReportRoute: typeof WallStreetReportRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AgentsDeskRoute: typeof AgentsDeskRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  QuantRlLabRoute: typeof QuantRlLabRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SignalsIndexRoute: typeof SignalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wall-street-report': {
      id: '/wall-street-report'
      path: '/wall-street-report'
      fullPath: '/wall-street-report'
      preLoaderRoute: typeof WallStreetReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-api': {
      id: '/my-api'
      path: '/my-api'
      fullPath: '/my-api'
      preLoaderRoute: typeof MyApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-pilot': {
      id: '/ai-pilot'
      path: '/ai-pilot'
      fullPath: '/ai-pilot'
      preLoaderRoute: typeof AiPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/': {
      id: '/signals/'
      path: '/signals'
      fullPath: '/signals/'
      preLoaderRoute: typeof SignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quant/rl-lab': {
      id: '/quant/rl-lab'
      path: '/quant/rl-lab'
      fullPath: '/quant/rl-lab'
      preLoaderRoute: typeof QuantRlLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/desk': {
      id: '/agents/desk'
      path: '/agents/desk'
      fullPath: '/agents/desk'
      preLoaderRoute: typeof AgentsDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPilotRoute: AiPilotRoute,
  MyApiRoute: MyApiRoute,
  PendingRoute: PendingRoute,
  PricingRoute: PricingRoute,
  WallStreetReportRoute: WallStreetReportRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AgentsDeskRoute: AgentsDeskRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  QuantRlLabRoute: QuantRlLabRoute,
  AdminIndexRoute: AdminIndexRoute,
  SignalsIndexRoute: SignalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
